services:
  database:
    container_name: postgresdb
    hostname: postgresdb
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  dbadmin:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - 8080:8080
  broker:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./broker_data:/var/lib/rabbitmq/
      - ./rabbit-init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit-init/definitions.json:/etc/rabbitmq/definitions.json:ro
  rtsp:
    image: aler9/rtsp-simple-server
    container_name: rtsp
    restart: always
    ports:
      - 8554:8554
  web-api:
    ports:
      - 8090:8090
    build:
      context: ./sensi-web-api
      dockerfile: ./Dockerfile
      restart: always
    depends_on:
      - database
      - broker
      - rtsp
    environment:
      - JDBC_DATABASE_URL=jdbc: postgresql://postgresdb/postgres?user=postgres&password=postgres